# Generated by Django 3.0.4 on 2020-03-21 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_auto_20200320_1150'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'user profile', 'verbose_name_plural': 'user profiles'},
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='photo',
        ),
    ]
